In [16]:
# Basic liberaries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# sklearn imports

from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import train
# Ignore warnings

import warnings
warnings.filterwarnings('ignore')

In [2]:
data = pd.read_csv('Housing.csv')
data.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [3]:
data.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [4]:
data.dtypes

price                int64
area                 int64
bedrooms             int64
bathrooms            int64
stories              int64
mainroad            object
guestroom           object
basement            object
hotwaterheating     object
airconditioning     object
parking              int64
prefarea            object
furnishingstatus    object
dtype: object

In [7]:
# filtering the cat columns

# cat_col=[]

# for cols in data.columns:
#     if data[cols].dtype =='O':
#         cat_cols.append(cols)
# print(cat_cols)

# List comprehension to find the list of categorical columns

cat_cols = [cols for cols in data.columns if data[cols].dtype=='O']
cat_cols

['mainroad',
 'guestroom',
 'basement',
 'hotwaterheating',
 'airconditioning',
 'prefarea',
 'furnishingstatus']

In [11]:
# unique values for categorical columns

for cols in cat_cols:
    print(cols,':',data[cols].unique())

mainroad : ['yes' 'no']
guestroom : ['no' 'yes']
basement : ['no' 'yes']
hotwaterheating : ['no' 'yes']
airconditioning : ['yes' 'no']
prefarea : ['yes' 'no']
furnishingstatus : ['furnished' 'semi-furnished' 'unfurnished']

#  OneHotEncoder

In [19]:
# Using OneHotEncoder

sk_encoder = OneHotEncoder()
sk_encoded_data = sk_encoder.fit_transform(data[cat_cols])
sk_encoded_data

<545x15 sparse matrix of type '<class 'numpy.float64'>'
	with 3815 stored elements in Compressed Sparse Row format>

In [20]:
# the above data is in compresed format
# unzip it
sk_encoder = OneHotEncoder(sparse_output=False)
sk_encoded_data = sk_encoder.fit_transform(data[cat_cols])
sk_encoded_data

array([[0., 1., 1., ..., 1., 0., 0.],
       [0., 1., 1., ..., 1., 0., 0.],
       [0., 1., 1., ..., 0., 1., 0.],
       ...,
       [0., 1., 1., ..., 0., 0., 1.],
       [1., 0., 1., ..., 1., 0., 0.],
       [0., 1., 1., ..., 0., 0., 1.]])

In [21]:
# the return type above is array
# lets convert to DF
sk_encoder = OneHotEncoder(sparse_output=False)
sk_encoded_data = sk_encoder.fit_transform(data[cat_cols])
sk_encoded_data = pd.DataFrame(sk_encoded_data)
sk_encoded_data

      0    1    2    3    4    5    6    7    8    9    10   11   12   13   14
0    0.0  1.0  1.0  0.0  1.0  0.0  1.0  0.0  0.0  1.0  0.0  1.0  1.0  0.0  0.0
1    0.0  1.0  1.0  0.0  1.0  0.0  1.0  0.0  0.0  1.0  1.0  0.0  1.0  0.0  0.0
2    0.0  1.0  1.0  0.0  0.0  1.0  1.0  0.0  1.0  0.0  0.0  1.0  0.0  1.0  0.0
3    0.0  1.0  1.0  0.0  0.0  1.0  1.0  0.0  0.0  1.0  0.0  1.0  1.0  0.0  0.0
4    0.0  1.0  0.0  1.0  0.0  1.0  1.0  0.0  0.0  1.0  1.0  0.0  1.0  0.0  0.0
..   ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...  ...
540  0.0  1.0  1.0  0.0  0.0  1.0  1.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0
541  1.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0  0.0  1.0  0.0
542  0.0  1.0  1.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0
543  1.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0  0.0
544  0.0  1.0  1.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0  1.0  0.0  0.0  0.0  1.0

[545 rows x 15 columns]

In [22]:
# from the above we are not getting columns names.
# lets get the column names

sk_encoder = OneHotEncoder(sparse_output=False)
sk_encoded_data = sk_encoder.fit_transform(data[cat_cols])
sk_encoded_data = pd.DataFrame(sk_encoded_data, columns=sk_encoder.get_feature_names_out())
sk_encoded_data.head()

,mainroad_no,mainroad_yes,guestroom_no,guestroom_yes,basement_no,basement_yes,hotwaterheating_no,hotwaterheating_yes,airconditioning_no,airconditioning_yes,prefarea_no,prefarea_yes,furnishingstatus_furnished,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0
1,0.0,1.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
2,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0,1.0,0.0,1.0,0.0
3,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0
4,0.0,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0

In [23]:
# from above we are getting yes and no
# we will drop the column (yes or no)

sk_encoder = OneHotEncoder(sparse_output=False, drop='first')
sk_encoded_data = sk_encoder.fit_transform(data[cat_cols])
sk_encoded_data = pd.DataFrame(sk_encoded_data, columns=sk_encoder.get_feature_names_out())
sk_encoded_data.head()

,mainroad_yes,guestroom_yes,basement_yes,hotwaterheating_yes,airconditioning_yes,prefarea_yes,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0
1,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0
2,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0
3,1.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0
4,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.0

In [24]:
# Every value is float
# let convert it to int

sk_encoder = OneHotEncoder(sparse_output=False, drop='first', dtype='int')
sk_encoded_data = sk_encoder.fit_transform(data[cat_cols])
sk_encoded_data = pd.DataFrame(sk_encoded_data, columns=sk_encoder.get_feature_names_out())
sk_encoded_data.head()

,mainroad_yes,guestroom_yes,basement_yes,hotwaterheating_yes,airconditioning_yes,prefarea_yes,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,1,0,0,0,1,1,0,0
1,1,0,0,0,1,0,0,0
2,1,0,1,0,0,1,1,0
3,1,0,1,0,1,1,0,0
4,1,1,1,0,1,0,0,0

In [25]:
# we only got cat data.
# we need to merge the cat and num data

sk_encoder = OneHotEncoder(sparse_output=False, drop='first', dtype='int')
sk_encoded_data = sk_encoder.fit_transform(data[cat_cols])
sk_encoded_data = pd.DataFrame(sk_encoded_data, columns=sk_encoder.get_feature_names_out())
sk_encoded_data = pd.concat([data.drop(cat_cols, axis=1),sk_encoded_data],axis=1)
sk_encoded_data.head()

,price,area,bedrooms,bathrooms,stories,parking,mainroad_yes,guestroom_yes,basement_yes,hotwaterheating_yes,airconditioning_yes,prefarea_yes,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,13300000,7420,4,2,3,2,1,0,0,0,1,1,0,0
1,12250000,8960,4,4,4,3,1,0,0,0,1,0,0,0
2,12250000,9960,3,2,2,2,1,0,1,0,0,1,1,0
3,12215000,7500,4,2,2,3,1,0,1,0,1,1,0,0
4,11410000,7420,4,1,2,2,1,1,1,0,1,0,0,0

# OneHotEncoder 2nd Method

In [26]:
# Pandas - get dummies

getdummies_df = pd.get_dummies(data, dtype='int', drop_first=True)
getdummies_df.head()

,price,area,bedrooms,bathrooms,stories,parking,mainroad_yes,guestroom_yes,basement_yes,hotwaterheating_yes,airconditioning_yes,prefarea_yes,furnishingstatus_semi-furnished,furnishingstatus_unfurnished
0,13300000,7420,4,2,3,2,1,0,0,0,1,1,0,0
1,12250000,8960,4,4,4,3,1,0,0,0,1,0,0,0
2,12250000,9960,3,2,2,2,1,0,1,0,0,1,1,0
3,12215000,7500,4,2,2,3,1,0,1,0,1,1,0,0
4,11410000,7420,4,1,2,2,1,1,1,0,1,0,0,0

#  Observation

* Use OneHotEncoder for large DF
* Use get dummies for small DF (less than ~ 100000)

# Another example for OneHotEncoder

In [28]:
penguin_data = sns.load_dataset('penguins')
penguin_data.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female

In [29]:
pcat_cols = [cols for cols in penguin_data.columns if penguin_data[cols].dtype =='O' ]
pcat_cols

['species', 'island', 'sex']

In [38]:
for cols in pcat_cols:
    print(cols,':',penguin_data[cols].unique())

species : ['Adelie' 'Chinstrap' 'Gentoo']
island : ['Torgersen' 'Biscoe' 'Dream']
sex : ['Male' 'Female' nan]

In [46]:
sk_encoder = OneHotEncoder(sparse_output=False, dtype='int',drop='first')
sk_encoded_data = sk_encoder.fit_transform(penguin_data[pcat_cols])
sk_encoded_data = pd.DataFrame(sk_encoded_data, columns=sk_encoder.get_feature_names_out())
sk_encoded_data = pd.concat([penguin_data.drop(pcat_cols, axis=1),sk_encoded_data],axis=1)
sk_encoded_data.head()

,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,species_Chinstrap,species_Gentoo,island_Dream,island_Torgersen,sex_Male,sex_nan
0,39.1,18.7,181.0,3750.0,0,0,0,1,1,0
1,39.5,17.4,186.0,3800.0,0,0,0,1,0,0
2,40.3,18.0,195.0,3250.0,0,0,0,1,0,0
3,NaN,NaN,NaN,NaN,0,0,0,1,0,1
4,36.7,19.3,193.0,3450.0,0,0,0,1,0,0

In [43]:
getdummies_df = pd.get_dummies(penguin_data, dtype='int', drop_first=True)
getdummies_df.head()

,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,species_Chinstrap,species_Gentoo,island_Dream,island_Torgersen,sex_Male
0,39.1,18.7,181.0,3750.0,0,0,0,1,1
1,39.5,17.4,186.0,3800.0,0,0,0,1,0
2,40.3,18.0,195.0,3250.0,0,0,0,1,0
3,NaN,NaN,NaN,NaN,0,0,0,1,0
4,36.7,19.3,193.0,3450.0,0,0,0,1,0